# Generated by Django 3.2.7 on 2021-09-20 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DWS_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
