# Generated by Django 3.2.7 on 2021-09-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWS_chatbot', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='User', max_length=15),
        ),
    ]
